name: Deploy Project
on:
  # push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # get code from repo to server as repo is just a folder not server [we can't run commands in it i.e npm install]
      - name: Get Code From repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code From repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run npm install
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy
        run: echo 'deploy'
